

services:
  # 1. SERVIZIO PHP-FPM
  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/var/www/html 
    depends_on:
      - mariadb 
    ports:
      - "9000:9000" 
    container_name: symfony_php
    environment:
      DATABASE_URL: "mysql://user:password@mariadb:3306/symfony?serverVersion=mariadb-12.0.0"

  # 2. SERVIZIO NGINX
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - php 
    container_name: symfony_nginx

  # 3. SERVIZIO DATABASE (MariaDB)
  mariadb:

    image: mariadb:12.0
    container_name: symfony_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:


   